//
//  HomeConfigurator.swift
//  MarvelViper
//
//  Created by Edgard Vargas on 19/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
//
extension HomeViewController {

//    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
//        router.passDataToNextScene(segue: segue)
//    }
    //esto solo se usa con el story board
//    override func awakeFromNib() {
//        super.awakeFromNib()
//        HomeConfigurator.configure(viewController: self)
//    }

    static func instantiate() -> HomeViewController {
        
        let viewController = HomeViewController()
        HomeConfigurator.configure(viewController: viewController)
        return viewController
    }

}

class HomeConfigurator {

    // MARK: - Configuration

    static func configure(viewController: HomeViewController) {

        let presenter = HomePresenter()
        presenter.viewController = viewController

        let interactor = HomeInteractor()
        interactor.presenter = presenter

        let router = HomeRouter()
        router.viewController = viewController
        router.interactor = interactor
        
        viewController.interactor = interactor
        viewController.router = router
    }

}
