//
//  HomePresenter.swift
//  MarvelViper
//
//  Created by Edgard Vargas on 19/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class HomePresenter {

    weak var viewController: HomeViewController?

    // MARK: - Presentation logic
    
    func presentfetchHeroes(response: HomeScene.fetchHeroes.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        let displayedHeroes = response.heroes?.map { hero in
            HomeScene.fetchHeroes.ViewModel.DisplayHero(id: hero.id, name: hero.name, photo: "\(hero.thumbnail.path).\(hero.thumbnail.thumbnailExtension)")
        }
        
        
        viewController?.displayfetchHeroes(viewModel: HomeScene.fetchHeroes.ViewModel(displayedHeroes: displayedHeroes ?? []))
    }
    
    func presentAlertError(response: HomeScene.AlertError.Response) {
        viewController?.displayAlertError(viewModel: HomeScene.AlertError.ViewModel(
            message: response.error.localizedDescription
        ))
    }

}
