//
//  HomeDetailScenePresenter.swift
//  MarvelViper
//
//  Created by EdgardVS on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class HomeDetailScenePresenter {

    weak var viewController: HomeDetailSceneViewController?

    // MARK: - Presentation logic
    
    func presentfetchHero(response: HomeDetailSceneScene.fetchHero.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        //viewController?.displayfetchHero(viewModel: HomeDetailSceneScene.fetchHero.ViewModel())
        let displayedHero = response.hero?.map { hero in
            HomeDetailSceneScene.fetchHero.ViewModel.DisplayHero(id: hero.id, name: hero.name, description: hero.description, photo: "\(hero.thumbnail.path).\(hero.thumbnail.thumbnailExtension)")
        }
        
        viewController?.displayfetchHero(viewModel: HomeDetailSceneScene.fetchHero.ViewModel(displayedHeroes: displayedHero ?? []))
        
    }
    
    func presentAlertError(response: HomeDetailSceneScene.AlertError.Response) {
        viewController?.displayAlertError(viewModel: HomeDetailSceneScene.AlertError.ViewModel(
            message: response.error.localizedDescription
        ))
    }

}
