//
//  MovieModels.swift
//  MarvelViper
//
//  Created by Edgard Vargas on 19/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum MovieScene {
    
    enum fetchMovies {
        
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
            struct DisplayedSomething {
                // let title: String
            }
            // let displayedSomethings: [DisplayedSomething]
        }
        
    }
    
    enum AlertError {
        
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let message: String
        }
        
    }

}
