//
//  MovieConfigurator.swift
//  MarvelViper
//
//  Created by Edgard Vargas on 19/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension MovieViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        MovieConfigurator.configure(viewController: self)
    }

    static func instantiate() -> MovieViewController {
        let storyboard = UIStoryboard(name: "Movie", bundle: nil)
        let viewController = storyboard.instantiateInitialViewController() as! MovieViewController
        return viewController
    }

}

class MovieConfigurator {

    // MARK: - Configuration

    static func configure(viewController: MovieViewController) {

        let presenter = MoviePresenter()
        presenter.viewController = viewController

        let interactor = MovieInteractor()
        interactor.presenter = presenter

        let router = MovieRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
