//
//  MovieInteractor.swift
//  MarvelViper
//
//  Created by Edgard Vargas on 19/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class MovieInteractor {

    var presenter: MoviePresenter?

    // MARK: - Object variables

    // var loadAction: loadAction!

    // MARK: - Business logic

    func dofetchMovies(request: MovieScene.fetchMovies.Request) {
        // NOTE: Pass the result to the Presenter
        do {
            presenter?.presentfetchMovies(response: MovieScene.fetchMovies.Response())
        } catch {
            presenter?.presentAlertError(response: MovieScene.AlertError.Response(
                error: error
            ))
        }
    }

}
