//
//  MoviePresenter.swift
//  MarvelViper
//
//  Created by Edgard Vargas on 19/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class MoviePresenter {

    weak var viewController: MovieViewController?

    // MARK: - Presentation logic
    
    func presentfetchMovies(response: MovieScene.fetchMovies.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        viewController?.displayfetchMovies(viewModel: MovieScene.fetchMovies.ViewModel())
    }
    
    func presentAlertError(response: MovieScene.AlertError.Response) {
        viewController?.displayAlertError(viewModel: MovieScene.AlertError.ViewModel(
            message: response.error.localizedDescription
        ))
    }

}
