//
//  ComicListRouter.swift
//  MarvelViper
//
//  Created by EdgardVS on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

class ComicListRouter {

    weak var viewController: ComicListViewController?
    weak var interactor: ComicListInteractor?

    // MARK: - Navigation

    func navigateToComic(comicId: Int) {
        let destinationViewController = ComicViewController.instantiate(comicId: comicId)
        viewController?.navigationController?.pushViewController(destinationViewController, animated: true)
    }
    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // if let destinationViewController = segue.destination as? SomewhereViewController {
        //     destinationViewController.interactor.something = interactor?.something
        // }
    }

}
