//
//  ComicListPresenter.swift
//  MarvelViper
//
//  Created by EdgardVS on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class ComicListPresenter {

    weak var viewController: ComicListViewController?

    // MARK: - Presentation logic
    
    func presentfetchComics(response: ComicListScene.fetchComics.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        
        //viewController?.displayfetchComics(viewModel: ComicListScene.fetchComics.ViewModel())
    }
    
    func presentAlertError(response: ComicListScene.AlertError.Response) {
        viewController?.displayAlertError(viewModel: ComicListScene.AlertError.ViewModel(
            message: response.error.localizedDescription
        ))
    }

}
