//
//  ComicListInteractor.swift
//  MarvelViper
//
//  Created by EdgardVS on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class ComicListInteractor {

    var presenter: ComicListPresenter?

    // MARK: - Object variables

    // var loadAction: loadAction!

    // MARK: - Business logic

    func dofetchComics(request: ComicListScene.fetchComics.Request) {
        // NOTE: Pass the result to the Presenter
        MarvelService.shared.getComics { result in
            let comics = result.data.results
            self.presenter?.presentfetchComics(response: ComicListScene.fetchComics.Response(comics: comics))
        }
    }

}
