//
//  ComicListViewController.swift
//  MarvelViper
//
//  Created by EdgardVS on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

class ComicListViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {

    var interactor: ComicListInteractor!
    var router: ComicListRouter!

    // MARK: - Object variables

    // NOTE: Only store objects here if required
    private var displayedSomethings: [ComicListScene.fetchComics.ViewModel.DisplayedComic] = []

    // MARK: - Inteface objects

    

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Comics"
        setupView()
        //doTestApi()
        dofetchComics()
    }

    func setupView() {
        // NOTE: Setup the view on load
        // somethingLabel.textColor = UIColor.blue
    }

    // MARK: - Interaction handling

    // @IBAction func buttonPressed() { ...

    // MARK: - Event handling

    func doTestApi() {
        MarvelService.shared.getComics { result in
            print(result.data.results[0].title)
        }
    }
    
    func dofetchComics() {
        // NOTE: Ask the Interactor to do some work
        // NOTE: Start loading animation here
        interactor.dofetchComics(request: ComicListScene.fetchComics.Request())
    }

    // MARK: - Display logic

    func displayfetchComics(viewModel: ComicListScene.fetchComics.ViewModel) {
        // NOTE: Display the result from the Presenter
        // NOTE: Stop loading animation here
        // displayedSomething = viewModel.displayedSomething
        // tableView.reloadData()
    }
    
    func displayAlertError(viewModel: ComicListScene.AlertError.ViewModel) {
        // NOTE: Stop loading animation here
        let alert = UIAlertController(title: "Error", message: viewModel.message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        present(alert, animated: true, completion: nil)
    }

    // MARK: - TableView DataSource Methods

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedSomethings.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let displayedSomething = displayedSomethings[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: ComicListTableViewCell.identifier, for: indexPath) as! ComicListTableViewCell
        // cell.titleLabel.text = displayedSomething.title
        return cell
    }

    // MARK: - TableView Delegate Methods

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }

}
