//
//  ComicListModels.swift
//  MarvelViper
//
//  Created by EdgardVS on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum ComicListScene {
    
    enum fetchComics {
        
        struct Request {
        }
        struct Response {
            let comics : [ResultComic]?
            
        }
        struct ViewModel {
            struct DisplayedComic {
                let title: String
                let photo: String
            }
            let displayedComics: [DisplayedComic]
        }
        
    }
    
    enum AlertError {
        
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let message: String
        }
        
    }

}
