//
//  ComicModels.swift
//  MarvelViper
//
//  Created by Edgard Vargas on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum ComicScene {
    
    enum fetchComic {
        
        struct Request {
        }
        struct Response {
            let comic: [ResultComic]?
        }
        struct ViewModel {
            struct DisplayComic {
                let id: Int
                let name: String
                let description: String
                let photo: String
            }
            let displayComic: [DisplayComic]
        }
        
    }
    
    enum AlertError {
        
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let message: String
        }
        
    }

}
